### ISSUE TITLE
Delay in Detecting Mock location is OFF

### ISSUE THREAD

**Issue by praveenreddy9** [adkandari/react-native-mock-location-detector#11]
const isLocationMocked = await RNMockLocationDetector.checkMockLocationProvider();

when Mock Location is ON, **isLocationMocked** is getting true but if we turn OFF the mock location **isLocationMocked** is getting true for multiple time then its updating to False.

**Comment by adkandari** [comment]
Hi, I am sorry I am not maintaining this library from quite sometime now. You can check a new fork of this one https://github.com/jpudysz/react-native-turbo-mock-location-detector, looks like it is maintained regularly
