### ISSUE TITLE
Does this support javascript?

### ISSUE THREAD

**Issue by jhexdejesus1** [adkandari/react-native-mock-location-detector#13]
Hi,

I'm new to react native and I'm currently using JavaScript. When I added this dependencies it's giving me errors.

ERROR: Unexpected identifier '_reactNativeMockLocationDetector'. Expected ';' after variable declaration.

I only added these lines and it gives me that error.

import RNMockLocationDetector from "react-native-mock-location-detector";

const isLocationMocked = await RNMockLocationDetector.checkMockLocationProvider();

This function is returning null

[Unhandled promise rejection: TypeError: null is not an object (evaluating '_reactNativeMockLocationDetector.default.checkMockLocationProvider')]

I would really appreciate the response.

**Comment by jhexdejesus1** [comment]
This function is returning null

[Unhandled promise rejection: TypeError: null is not an object (evaluating '_reactNativeMockLocationDetector.default.checkMockLocationProvider')]

**Comment by adkandari** [comment]
Hi, I am sorry I am not maintaining this library from quite sometime now. You can check a new fork of this one https://github.com/jpudysz/react-native-turbo-mock-location-detector, looks like it is maintained regularly
