### ISSUE TITLE
checkMockLocationProvider got 5 arguments expected 2

### ISSUE THREAD

**Issue by mughniaziz004** [adkandari/react-native-mock-location-detector#15]
I set the function checkMockLocationProvider with argument the function needed

but the function returned RNMockLocationDetector.checkMockLocationProvider got 5 arguments, expected 2

how should i to fix it ?

My RN project use : 0.62

**Comment by methineeinkan** [comment]
+1

**Comment by adkandari** [comment]
Hi, I am sorry I am not maintaining this library from quite sometime now. You can check a new fork of this one https://github.com/jpudysz/react-native-turbo-mock-location-detector, looks like it is maintained regularly
