### ISSUE TITLE
checkMockLocationProvider getting null in iOS

### ISSUE THREAD

**Issue by v1pu2** [adkandari/react-native-mock-location-detector#16]
I am getting mocked value in React native app. In android it is working but not in iOS. Project details are as below
 "react-native": "0.71.4",
 "react-native-mock-location-detector": "^2.0.0",
 "react-native-permissions": "^3.8.0",
 iOS - 16.2
Please help me to solve the issue. I want to detect fake location in my React native app.

**Comment by adkandari** [comment]
Hi @v1pu2 , I am sorry I am not maintaining this library from quite sometime now. You can check a new fork of this one https://github.com/jpudysz/react-native-turbo-mock-location-detector, looks like it is maintained regularly
