### ISSUE TITLE
Fatal Exception: java.lang.NullPointerException Attempt to invoke virtual method 'int android.content.Context.checkPermission(java.lang.String, int, int)' on a null object reference com.mocklocation.reactnative.RNMockLocationDetectorModule.checkMockLocationProvider

### ISSUE THREAD

**Issue by hanifmhd** [adkandari/react-native-mock-location-detector#4]
Google firebase crashlytics always detect this error
<img width="1138" alt="Screen Shot 2020-10-14 at 10 04 37" src="https://user-images.githubusercontent.com/15220788/95938830-e768df80-0e04-11eb-90b7-57c3b6b83dd6.png">

it points in class RNMockLocationDetectorModule line 59
<img width="952" alt="Screen Shot 2020-10-14 at 10 05 08" src="https://user-images.githubusercontent.com/15220788/95938913-1bdc9b80-0e05-11eb-8dce-66063fc7969e.png">

**Comment by adkandari** [comment]
Hi @hanifmhd , can you try the latest update and check if it works. I think the error must be device specific.

**Comment by thanhtu95** [comment]
same issue

**Comment by adkandari** [comment]
Hi, I am sorry I am not maintaining this library for quite some time now.
You can check a new fork of this one
https://github.com/jpudysz/react-native-turbo-mock-location-detector, looks
like it is maintained regularly.
