### ISSUE TITLE
Could not find a declaration file for module 'react-native-mock-location-detector'.

### ISSUE THREAD

**Issue by Edgamer97** [adkandari/react-native-mock-location-detector#5]
When I import the module I get the above mentioned error. It seems to be a typescript based error but I am not using typescript but just javascript based project. Any solution for this?

**Comment by xDAnkit** [comment]
@Edgamer97 - Added `TypeScript` support in this PR : https://github.com/adkandari/react-native-mock-location-detector/pull/6
@adkandari - Please have a look at PR to update

**Comment by adkandari** [comment]
Thank you so much @xDAnkit . I have approved the PR. 🙌

@Edgamer97 let me confirm if this works and I will close the ticket.

**Comment by xDAnkit** [comment]
Thank you @adkandari for merging the PR. Please do release an updated NPM package for the same for [react-native-mock-location-detector
](https://www.npmjs.com/package/react-native-mock-location-detector)

Once done please let me know and i'll let at my end.

**Comment by RahafShayeb** [comment]
I'm still having the same problem when I import the module, any solutions?

**Comment by xDAnkit** [comment]
@RahafShayeb - I have found that the updated code is not yet published on npm. Please install your package.json and point the current plugin to `https://github.com/adkandari/react-native-mock-location-detector.git`

Ex : ` "react-native-mock-location-detector": "https://github.com/adkandari/react-native-mock-location-detector.git"`

**Comment by xDAnkit** [comment]
@adkandari - Can you please update your `npm` package

**Comment by adkandari** [comment]
Thanks. I will do it this week.

**Comment by adkandari** [comment]
> @adkandari - Can you please update your `npm` package

Hey @xDAnkit , so sorry for late update. I have pushed the latest update on npm
