### ISSUE TITLE
Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.

### ISSUE THREAD

**Issue by snowfluke** [adkandari/react-native-mock-location-detector#7]
Need upgrade

```
WARNING: Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
It will be removed in version 5.0 of the Android Gradle plugin.
For more information, see http://d.android.com/r/tools/update-dependency-configurations.html.
```

**Comment by adkandari** [comment]
Hey @snowfluke , we are not using 'compile' in build.gradle.

It might be coming from a local library, or the google gms locations, you can update the version for this and hopefully warning will go away

**Comment by mayran-aragao** [comment]
hey guys, I'm having the following problem =>>>

ON INSTALL= >>

 code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: undefined@undefined
npm ERR! Found: react-native@0.63.4
npm ERR! node_modules/react-native
npm ERR!   react-native@"0.63.4" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react-native@"^0.41.2" from react-native-mock-location-detector@2.0.0
npm ERR! node_modules/react-native-mock-location-detector
npm ERR!   react-native-mock-location-detector@"^2.0.0" from the root project

WHEN I FORCE THE INSTALL AND EXECUTE THE FUNCTION =>>

[Unhandled promise rejection: TypeError: null is not an object (evaluating '_reactNativeMockLocationDetector.default.checkMockLocationProvider')]
at node_modules/react-native-elements/dist/buttons/Button.js:32:466 in Button
at node_modules/react-native/Libraries/Pressability/Pressability.js:691:17 in _performTransitionSideEffects
at node_modules/react-native/Libraries/Pressability/Pressability.js:628:6 in _receiveSignal
at node_modules/react-native/Libraries/Pressability/Pressability.js:524:8 in responderEventHandlers.onResponderRelease
