### ISSUE TITLE
Nothing is happening when I ran the code

### ISSUE THREAD

**Issue by Yandamuri** [adkandari/react-native-mock-location-detector#8]
Location permission is turned on and ran below line

     const isLocationMocked = await RNMockLocationDetector.checkMockLocationProvider();

But nothing is happening. In fact, further execution is being continued.

"react-native": "0.64.2",
 "react-native-mock-location-detector": "2.0.0"

Am I missing anything here?

**Comment by adkandari** [comment]
Hi, I am sorry I am not maintaining this library from quite sometime now. You can check a new fork of this one https://github.com/jpudysz/react-native-turbo-mock-location-detector, looks like it is maintained regularly
