### ISSUE TITLE
Cannot detect mock location 

### ISSUE THREAD

**Issue by ycdaskin** [adkandari/react-native-mock-location-detector#9]
It works when i run my app after running fake gps app. But when i run my app first and fake gps app second, it doesn't detect mock location. And this creates a very simple vulnerability for my application.

**Comment by adkandari** [comment]
Hi, I am sorry I am not maintaining this library from quite sometime now. You can check a new fork of this one https://github.com/jpudysz/react-native-turbo-mock-location-detector, looks like it is maintained regularly
